name: CICD

env:
  repository: jannemattila/webapp-monitoring
  image: 1.0.${{ github.run_number }}
  context: .
  dockerfile: src/WebApp/Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        id: docker_hub_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context }}
          file: ${{ env.dockerfile }}
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.repository }}:latest
            ${{ env.repository }}:${{ env.image }}
            
      - name: Digest
        run: echo ${{ steps.docker_hub_build.outputs.digest }}
